// frontend/solidjs/src/components/Thumbnail.tsx
// import { createResource } from "solid-js";
import { MediaDisplayPropsFragment } from "../queries/types/graphql";

export type ThumbnailProps = {
  media: MediaDisplayPropsFragment;
};

const Thumbnail = (props: ThumbnailProps) => {
  const { id, processed } = props.media;
  // const [media] = createResource(() => {});

  const src = processed ? `/m/${id}/0` : `/m/${id}`;
  //  return <div class={`bg-cover bg-[url('${src}')]`}></div>;
  return <img src={src} />;
};

export default Thumbnail;

// frontend/react/src/ui/components/Thumbnail.tsx
import { MediaDisplayPropsFragment } from "../../queries/types/graphql";
import ThumbnailImage from "./ThumbnailImage";
import ThumbnailVideo from "./ThumbnailVideo";
import ThumbnailGif from "./ThumbnailGif";
import MediaTypes from "../../types/mediaType";

export type ThumbnailProps = {
  media: MediaDisplayPropsFragment; 
  thumbnailClickedCallback: (media: MediaDisplayPropsFragment) => void;
};

const Thumbnail = (props: ThumbnailProps) => {
  switch (props.media.mediaType) {
    case MediaTypes.gif : return <ThumbnailGif {...props} />; 
    case MediaTypes.video : return <ThumbnailVideo {...props} />; 
    default: return <ThumbnailImage {...props}/>; 
  }
};
export default Thumbnail;
