// frontend/src/components/Thumbnail.tsx
import React from "react";
import { AllMedia_allMedia as Media } from "../queries/types/AllMedia";
import { LazyLoadImage } from "react-lazy-load-image-component";

const Thumbnail: React.FC<Media> = (props) => {
  if (props.processed) {
    return (
      <LazyLoadImage alt={"/m/" + props.id + "/0"} effect="blur" src={"/m/" + props.id + "/1"} />
    );
  } else {
    return <img src={"/m/" + props.id} width="100%" alt={props.id.toString()} />;
  }
};
export default Thumbnail;

// frontend/solidjs/src/components/Thumbnail.tsx
// import { createResource } from "solid-js";
import { MediaDisplayPropsFragment } from "../queries/types/graphql";

export type ThumbnailProps = {
  media: MediaDisplayPropsFragment;
};

const Thumbnail = (props: ThumbnailProps) => {
  const { id, processed } = props.media;
  // const [media] = createResource(() => {});

  const src = processed ? `/m/${id}/0` : `/m/${id}`;
  //  return <div class={`bg-cover bg-[url('${src}')]`}></div>;
  return <img src={src} />;
};

export default Thumbnail;
