// frontend/solidjs/src/pages/Feed.tsx
import type { Client } from "@urql/core";
import { For } from "solid-js";
import { createResource } from "solid-js";
import { AllMediaQuery } from "../queries/types/graphql";
import AllMediaQueryString from "../queries/AllMediaQuery";
import Thumbnail from "../components/Thumbnail";

export type FeedProps = {
  client: Client;
};

const Feed = (props: FeedProps) => {
  const [mediaList] = createResource(() =>
    props.client
      .query<AllMediaQuery>(AllMediaQueryString)
      .toPromise()
      .then(({ data }) => data.allMedia)
      .catch((err) => {
        console.log(err);
        return [];
      }),
  );

  return (
    <div class="grid xl:grid-cols-5 md:grid-cols-3 sm:grid-cols-1 gap-4">
      <For each={mediaList()}>{(media) => <Thumbnail media={media} />}</For>
    </div>
  );
};

export default Feed;

// frontend/src/pages/Feed.tsx
import React from "react";
import { useQuery } from "@apollo/client";
import { GridList, GridListTile } from "@material-ui/core";
import allMediaQuery from "../queries/allMediaQuery";
import { AllMediaQuery } from "../queries/types/graphql";
import Thumbnail from "../components/Thumbnail";

export default function Feed() {
  const { loading, error, data } = useQuery<AllMediaQuery>(allMediaQuery);
  if (loading) return <p>Loading... </p>;
  if (error) return <p>Error! :((( </p>;

  return (
    <GridList cellHeight={300} cols={3}>
      {data &&
        data.allMedia.map((media) => (
          <GridListTile key={media.id} cols={1}>
            <Thumbnail {...media} />
          </GridListTile>
        ))}
    </GridList>
  );
}
